config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  devise_for :users
  root "menus#index"
  resources :users
  resources :menus
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :items, dependent: :destroy
  belongs_to :unit, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  validates :amount, presence: true
  validates :menu_id, presence: true
  validates :ingredient_id, presence: true

  has_many :menu_items, foreign_key: 'item_id', dependent: :destroy   #中間テーブルをthroughより先に書く
  has_many :menus, through: :menu_items
  belongs_to :ingredient
  # has_one :unit, through: :ingredient
  accepts_nested_attributes_for :menus
  accepts_nested_attributes_for :menu_items
  accepts_nested_attributes_for :ingredient
  # accepts_nested_attributes_for :ingredient, allow_destroy: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :menu_items, foreign_key: 'menu_id', dependent: :destroy   #中間テーブルをthroughより先に書く
  has_many :items, through: :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  belongs_to :item
end

app/models/unit.rb
class Unit < ApplicationRecord
  validates :unit, presence: true, uniqueness: true
  validates :ingredient_id, presence: true

  has_many :ingredients
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 8 }

  has_many :menus, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_user

  def index
    @items = Item.all
    # @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @item.menus.build
    @item.menu_items.build
    # @item.ingredient.build
    # @item.build_menus
    # @item.build_menu_items

    @item.build_ingredient
  end

  def create
    @item = Item.new(item_params)
    
    # binding.pry
    if @item.save
      redirect_to root_path, notice: "編集が完了しました"
    else
      binding.pry
      flash.now[:alert] = "登録に失敗しました"
      render :new, alert: "登録に失敗しました"
    end
  end

private
  # def item_params
  #   params.require(:item).permit(:amount, :menu_id, :ingredient_id)
  # end

  # def item_params
  #   params.require(:item).permit(:amount, ingredient_attributes: [:id, :ingredient_name])
  #   params.require(:item).permit(ingredient_attributes: [:id, :ingredient_name])
  # end

  def item_params
    params.require(:item).permit(:amount, :menu_id, :ingredient_id, menus_attributes: [:id, :menu_name, :user_id], menu_items_attributes: [:id, :menu_id, :item_id], ingredient_attributes: [:id, :ingredient_name])
    # params.require(:item).permit(:amount, :menu_id, :ingredient_id, menus_attributes: [:id, :menu_name, :user_id], menu_items_attributes: [:id, :menu_id, :item_id], ingredient_attributes: [:id, :ingredient_name]).merge(user_id: current_user.id)
    # params.require(:item).permit(
    #   :amount,
    #   :menu_id,
    #   :ingredient_id,
    #   ingredient_attributes: [:id,
    #                           :ingredient_name]
    #   )
    #      .merge(user_id: current_user.id)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    # @menus = Menu.all
    # @menu = Menu.find(params[:id])
    @items = Item.all
  end

  def new
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :user_id)
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.haml
.container.main
  %h3
    お買い物　一覧ページ

  .table-responsive
    %table.table.table-hover
      %tr
        %th
          食材名
        %th
          数量
        %th
          単位
        %th
          変更
      - @items.each do |item|
        %tr
          -# %td
            -# = form_with model: @group, local: true do |f|
            -#   = f.collection_check_boxes :user_ids, User.all, :id, :name
          %td
            = item.ingredient.ingredient_name
          %td
            = item.amount
          %td
            = Unit.find_by(ingredient_id: item.ingredient.id).unit
          %td
            = link_to "#" do
              %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
                変更
              %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
                削除
        -# %tr
        -#   %td
        -#     カレー粉
        -#   %td
        -#     1
        -#   %td
        -#     箱
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     玉ねぎ
        -#   %td
        -#     4
        -#   %td
        -#     個
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     人参
        -#   %td
        -#     2
        -#   %td
        -#     本
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     合い挽き肉
        -#   %td
        -#     300
        -#   %td
        -#     g
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     うどん
        -#   %td
        -#     3
        -#   %td
        -#     玉
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     牛薄切り肉
        -#   %td
        -#     200
        -#   %td
        -#     g
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     青ネギ
        -#   %td
        -#     1
        -#   %td
        -#     束
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     そば
        -#   %td
        -#     3
        -#   %td
        -#     玉
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     キャベツ
        -#   %td
        -#     0.5
        -#   %td
        -#     個
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除
        -# %tr
        -#   %td
        -#     豚バラ肉
        -#   %td
        -#     100
        -#   %td
        -#     g
        -#   %td
        -#     = link_to "#" do
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         変更
        -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
        -#         削除

app/views/items/new.html.haml
.container.new
  %h3 メニュー追加ページ

  = form_with model: @item, local: true do |f|
    = f.fields_for :menus, @item.menus do |ff|
      = ff.text_field :menu_name, placeholder: '料理名'
    .br
    = f.fields_for :ingredient, @item.ingredient do |fff|
      = fff.text_field :ingredient_name, placeholder: '食材名'
    = f.text_field :amount, placeholder: '数量'
    .br
    %button{type: "submit", class:'btn btn-success'}
      追加

  -# = f.fields_for :ingredient, @item.build_ingredient do |ff|
  -# = f.text_field :menu_id, placeholder: 'menu_id'
  -# = f.text_field :ingredient_id, placeholder: 'ingredient_id'

  -# %form
  -#   %input{type: 'text', placeholder: '料理名'}
  -#   .br
  -#   %input{type: 'text', placeholder: '食材名'}
  -#   %input{type: 'text', placeholder: '数量'}
  -#   %input{type: 'text', placeholder: '単位'}
  -#   .br
  -#   %input{type: 'text', placeholder: '食材名'}
  -#   %input{type: 'text', placeholder: '数量'}
  -#   %input{type: 'text', placeholder: '単位'}
  -#   .br
  -#   %input{type: 'text', placeholder: '食材名'}
  -#   %input{type: 'text', placeholder: '数量'}
  -#   %input{type: 'text', placeholder: '単位'}
  -#   .br
  -#   %input{type: 'text', placeholder: '食材名'}
  -#   %input{type: 'text', placeholder: '数量'}
  -#   %input{type: 'text', placeholder: '単位'}
  -#   .br
  -#   %input{type: 'text', placeholder: '食材名'}
  -#   %input{type: 'text', placeholder: '数量'}
  -#   %input{type: 'text', placeholder: '単位'}
  -#   .br
  -#   %button{type: "submit", class:'btn btn-success'}
  -#     追加

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShoppingForCook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/notifications'
    .container
      .header
        %h3
          Shopping for Cook
        = link_to menus_path, method: :get do
          %button{type: "submit", class:'btn btn-success'}
            Menu一覧
        = link_to items_path, method: :get do
          %button{type: "submit", class:'btn btn-success'}
            買い物リスト
        - if user_signed_in?
          = link_to edit_user_path(current_user.id), class:"userName" do
            = current_user.nickname
    = yield
    .container
      .footer
        .links
          = link_to "https://twitter.com/" do
            %i.fab.fa-twitter
              twitter
          = link_to "https://www.instagram.com/?hl=ja" do
            %i.fab.fa-instagram
              Instagram
          = link_to "https://www.youtube.com" do
            %i.fab.fa-youtube
              youtube
          = link_to "https://line.me/ja/" do
            %i.fab.fa-line
              line

app/views/menus/index.html.haml
.container.main
  %h3
    料理メニュー　一覧ページ

  = link_to new_item_path, class:"link--new", method: :get do
    %button{type: "submit", class:'btn btn-success'}
      メニューを追加する

  .table-responsive
    %table.table.table-hover
      %tr
        %th
          料理名
        %th
          食材名
        %th
          数量
        %th
          単位
        %th
          変更
      - @items.each do |item|
        %tr
          %td
            = Menu.find_by(id: item.menu_id).menu_name
          %td
            = item.ingredient.ingredient_name
          %td
            = item.amount
          %td
            = Unit.find_by(ingredient_id: item.ingredient.id).unit
          %td
            = link_to "#" do
              %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
                変更
              %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
                削除

      -# %tr
      -#   %td
      -#     キーマカレー
      -#   %td
      -#     カレー粉
      -#   %td
      -#     1
      -#   %td
      -#     箱
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     キーマカレー
      -#   %td
      -#     玉ねぎ
      -#   %td
      -#     4
      -#   %td
      -#     個
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     キーマカレー
      -#   %td
      -#     人参
      -#   %td
      -#     2
      -#   %td
      -#     本
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     キーマカレー
      -#   %td
      -#     合い挽き肉
      -#   %td
      -#     300
      -#   %td
      -#     g
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     肉うどん
      -#   %td
      -#     うどん
      -#   %td
      -#     3
      -#   %td
      -#     玉
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     肉うどん
      -#   %td
      -#     牛薄切り肉
      -#   %td
      -#     200
      -#   %td
      -#     g
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     肉うどん
      -#   %td
      -#     青ネギ
      -#   %td
      -#     1
      -#   %td
      -#     束
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     焼きそば
      -#   %td
      -#     そば
      -#   %td
      -#     3
      -#   %td
      -#     玉
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     焼きそば
      -#   %td
      -#     キャベツ
      -#   %td
      -#     0.5
      -#   %td
      -#     個
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除
      -# %tr
      -#   %td
      -#     焼きそば
      -#   %td
      -#     豚バラ肉
      -#   %td
      -#     100
      -#   %td
      -#     g
      -#   %td
      -#     = link_to "#" do
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         変更
      -#       %button{type: "submit", class:'btn btn-outline-secondary btn-sm'}
      -#         削除

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", root_path, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :nickname
        .FormField__input--normal
          = f.text_field :nickname, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'